<option value="Alang-Alang">Alang-alang</option>
<option value="Amantacop">Amantacop</option>
<option value="Ando">Ando</option>
<option value="Balacdas">Balacdas</option>
<option value="Balud">Balud</option>
<option value="Banuyo">Banuyo</option>
<option value="Baras">Baras</option>
<option value="Bato">Bato</option>
<option value="Bayobay">Bayobay</option>
<option value="Benowangan">Benowangan</option>
<option value="Bugas">Bugas</option>
<option value="Cabalagnan">Cabalagnan</option>
<option value="Cabong">Cabong</option>
<option value="Cagbonga">Cagbonga</option>
<option value="Calico-an">Calico-an</option>
<option value="Calingatngan">Calingatngan</option>
<option value="Campesao">Campesao</option>
<option value="Can-abong">Can-abong</option>
<option value="Can-aga">Can-aga</option>
<option value="Camada">Camada</option>
<option value="Canjaway">Canjaway</option>
<option value="Canlaray">Canlaray</option>
<option value="Canyopay">Canyopay</option>
<option value="Divinubo">Divinubo</option>
<option value="Hebacong">Hebacong</option>
<option value="Hindang">Hindang</option>
<option value="Lalawigan">Lalawigan</option>
<option value="Libuton">Libuton</option>
<option value="Locsoon">Locsoon</option>
<option value="Maybacong">Maybacong</option>
<option value="Maypangdan">Maypangdan</option>
<option value="Pepelitan">Pepelitan</option>
<option value="Pinanag-an">Pinanag-an</option>
<option value="Purok A">Purok A</option>
<option value="Purok B">Purok B</option>
<option value="Purok C">Purok C</option>
<option value="Purok D1">Purok D1</option>
<option value="Purok D2">Purok D2</option>
<option value="Purok E">Purok E</option>
<option value="Purok F">Purok F</option>
<option value="Purok G">Purok G</option>
<option value="Purok H">Purok H</option>
<option value="Punta Maria">Point Mary</option>
<option value="Sabang North">Sabang North</option>
<option value="Sabang South">Sabang South</option>
<option value="San Andres">San Andres</option>
<option value="San Gabriel">San Gabriel</option>
<option value="San Gregorio">San Gregorio</option>
<option value="San Jose">San Jose</option>
<option value="San Mateo">San Mateo</option>
<option value="San Pablo">San Pablo</option>
<option value="San Saturnino">San Saturnino</option>
<option value="Santa Fe">Santa Fe</option>
<option value="Siha">Siha</option>
<option value="Songco">Songco</option>
<option value="Sohutan">Sohutan</option>
<option value="Suribao">Suribao</option>
<option value="Surok">Surok</option>
<option value="Taboc">Taboc</option>
<option value="Tabunan">Tabunan</option>
<option value="Tamoso">Tamoso</option>
